### ISSUE TITLE
Auto open project

### ISSUE THREAD

**Issue by oscom** [bdkjones/CodeKitCodaPlugin#8]
in Coda2 my Project is a hole Wordpress instalation, in CodeKit i prefer to use only the theme folder as project source. Whit CodeKit2 it was no problem.
With CodeKit3 CK askes me to add the WP instalation as Project and and dump my old project with only the theme. Clicking on "chancel" and retourning to Coda, CK asks me again, and so on.

**Comment by bdkjones** [comment]
Set the project path in coda to the theme folder. That's what the plugin tells CodeKit to add.

Also make sure you're running the latest release of the plugin!

**Comment by oscom** [comment]
In some projects i am working with themes and plugins together, in this case it is not the best solution but for "themes only" i will do as you suggested

thx for the plugin
